[package]
name = "mal_plan"
version = "0.1.0"
authors = ["KaHLK <yeah-kris@hotmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
directories = "2.0.2"
attohttpc = "0.9.0"
indicatif = "0.13.0"